pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/chijioke-akaolisa-osadebe/.config/pgadmin4/config.json"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - HOME: /home/chijioke-akaolisa-osadebe
  - LANG: en_US.UTF-8
  - LOGNAME: chijioke-akaolisa-osadebe
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
  - SHELL: /bin/bash
  - USER: chijioke-akaolisa-osadebe
  - XDG_RUNTIME_DIR: /run/user/1000
  - GTK_MODULES: gail:atk-bridge
  - QT_ACCESSIBILITY: 1
  - XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - DEBUGINFOD_URLS: https://debuginfod.ubuntu.com 
  - DESKTOP_SESSION: ubuntu
  - GDMSESSION: ubuntu
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - GSM_SKIP_SSH_AGENT_WORKAROUND: true
  - IM_CONFIG_PHASE: 1
  - PWD: /home/chijioke-akaolisa-osadebe
  - QT_IM_MODULE: ibus
  - SESSION_MANAGER: local/chijioke-akaolisa-osadebe-HP-Pavilion-Laptop-14-ce0xxx:@/tmp/.ICE-unix/2662,unix/chijioke-akaolisa-osadebe-HP-Pavilion-Laptop-14-ce0xxx:/tmp/.ICE-unix/2662
  - SHLVL: 0
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - USERNAME: chijioke-akaolisa-osadebe
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - XDG_CURRENT_DESKTOP: Unity
  - XDG_MENU_PREFIX: gnome-
  - XDG_SESSION_CLASS: user
  - XDG_SESSION_DESKTOP: ubuntu
  - XDG_SESSION_TYPE: wayland
  - XMODIFIERS: @im=ibus
  - _: /usr/bin/gnome-session
  - MANAGERPID: 2435
  - INVOCATION_ID: fa9908587d4f4e54bfbc8352625cf16d
  - JOURNAL_STREAM: 8:16088
  - SYSTEMD_EXEC_PID: 2706
  - MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@wayland.service/memory.pressure
  - MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
  - GJS_DEBUG_OUTPUT: stderr
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GNOME_SETUP_DISPLAY: :1
  - DISPLAY: :0
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.G7IMW2
  - WAYLAND_DISPLAY: wayland-0
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 19222
  - CHROME_DESKTOP: pgadmin4.desktop
  - ORIGINAL_XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - ELECTRON_ENABLE_SECURITY_WARNINGS: false
  - GDK_BACKEND: x11
  - PGADMIN_INT_PORT: 40279
  - PGADMIN_INT_KEY: 07f26961-1c80-4086-b840-3c04333c3294
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.009 Sec
NOTE: Configuring authentication for DESKTOP mode.
pgAdmin 4 - Application Initialisation

======================================


2024-11-08 10:50:32,902: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 20.037 Sec
------------------------------------------
Total launch time of pgAdmin4: 20.794 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:40279/?key=07f26961-1c80-4086-b840-3c04333c3294
2024-11-08 10:50:34,943: WARNING	pgadmin:	There are no saved passwords

2024-11-08 13:22:22,079: ERROR	pgadmin:	Failed to execute query (execute_2darray) for the server #1 - DB:tsdb (Query-id: 398725):
Error Message:the connection is lost

2024-11-08 13:27:54,527: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:9808317(Query-id: 1811366):
Error Message:ERROR:  consuming input failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request. 



2024-11-08 13:27:54,527: ERROR	pgadmin:	Connection (id #9808317) lost for the server (#1) on database (tsdb)

2024-11-08 13:29:46,771: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:9808317(Query-id: 3924447):
Error Message:ERROR:  function openai_embed(unknown, unknown) does not exist
LINE 1: select openai_embed('text-embedding-3-small', 'I love New Yo...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts. 

SQL state: 42883
Character: 8

